#!/bin/bash

read -p "Enter File name for tests: " FILE
while : ; do
  clear
  ./node_modules/typescript/bin/tsc
  ./node_modules/.bin/mocha $(find test -path "*$FILE*.js")
  printf "[ q:exit | *:continue tests ($FILE) ]"
  read -n1 -s
  case "$REPLY" in
    "q") clear; break  ;; 
  esac
done